[tool.poetry]
name = "pomogui"
version = "0.1.0"
description = ""
authors = ["magnus <magnus@dahleide.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
yt-dlp = "^2023.7.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
